import { Router, Response } from 'express';
import { authMiddleware, AuthRequest } from '../middleware/auth';
import prisma from '../lib/prisma';

const router = Router();

interface Ingredient {
  amount: string | number;
  unit: string;
  name: string;
  note?: string;
}

interface Step {
  step: number;
  instruction: string;
  technique?: string;
}

interface GeneratedRecipeData {
  id: string;
  title: string;
  description: string;
  cuisineInspiration: string;
  mood: string;
  ingredients: Ingredient[];
  steps: Step[];
  prepTime: number;
  cookTime: number;
  difficulty: string;
  platingSuggestion: string;
  pairingSuggestion: string;
}

// GET /api/export/recipe/:id/text
router.get('/recipe/:id/text', authMiddleware, async (req: AuthRequest, res: Response): Promise<void> => {
  const userId = req.userId!;
  const { id } = req.params;

  try {
    const recipe = await prisma.generatedRecipe.findFirst({
      where: { id, userId },
    });

    if (!recipe) {
      res.status(404).json({ error: 'Recipe not found' });
      return;
    }

    const r = recipe as unknown as GeneratedRecipeData;
    const ingredients = (r.ingredients as Ingredient[]) ?? [];
    const steps = (r.steps as Step[]) ?? [];

    const ingredientLines = ingredients
      .map((ing) => `- ${ing.amount} ${ing.unit} ${ing.name}${ing.note ? ` — ${ing.note}` : ''}`)
      .join('\n');

    const stepLines = steps
      .map((s) => `${s.step}. ${s.instruction}${s.technique ? ` (${s.technique})` : ''}`)
      .join('\n');

    const text = `${r.title}
${r.description}

Ingredients:
${ingredientLines}

Method:
${stepLines}

Cooking time: ${r.prepTime}min prep · ${r.cookTime}min cook
Difficulty: ${r.difficulty}
Plating: ${r.platingSuggestion}
Pairing: ${r.pairingSuggestion}

Generated by Savora`;

    res.setHeader('Content-Type', 'text/plain; charset=utf-8');
    res.setHeader('Content-Disposition', `attachment; filename="${r.title.replace(/[^a-z0-9]/gi, '_')}.txt"`);
    res.send(text);
  } catch (err) {
    console.error('Export text error:', err);
    res.status(500).json({ error: 'Failed to export recipe' });
  }
});

// POST /api/export/recipe/:id/share-card
router.post('/recipe/:id/share-card', authMiddleware, async (req: AuthRequest, res: Response): Promise<void> => {
  const userId = req.userId!;
  const { id } = req.params;

  try {
    // Check subscription
    const subscription = await prisma.subscription.findUnique({ where: { userId } });
    if (!subscription || subscription.status !== 'reserve') {
      res.status(402).json({ gated: true, feature: 'share_card' });
      return;
    }

    const recipe = await prisma.generatedRecipe.findFirst({
      where: { id, userId },
    });

    if (!recipe) {
      res.status(404).json({ error: 'Recipe not found' });
      return;
    }

    const r = recipe as unknown as GeneratedRecipeData;
    const ingredients = (r.ingredients as Ingredient[]) ?? [];
    const top3 = ingredients.slice(0, 3).map((i) => i.name);

    // Generate SVG share card (canvas fallback)
    const svgWidth = 1080;
    const svgHeight = 1080;
    const titleLines = wrapText(r.title, 28);
    const titleY = 440;

    const ingredientItems = top3
      .map((name, i) => `<text x="540" y="${titleY + 120 + i * 48}" font-family="Georgia,serif" font-size="28" fill="#c4a882" text-anchor="middle">${escapeXml(name)}</text>`)
      .join('\n');

    const svg = `<?xml version="1.0" encoding="UTF-8"?>
<svg width="${svgWidth}" height="${svgHeight}" viewBox="0 0 ${svgWidth} ${svgHeight}" xmlns="http://www.w3.org/2000/svg">
  <rect width="${svgWidth}" height="${svgHeight}" fill="#1a1208"/>
  <!-- Title -->
  ${titleLines.map((line, i) => `<text x="540" y="${titleY + i * 72}" font-family="Georgia,serif" font-size="56" fill="#f5f0e8" text-anchor="middle" font-weight="400">${escapeXml(line)}</text>`).join('\n  ')}
  <!-- Ingredients -->
  ${ingredientItems}
  <!-- Mood badge -->
  <rect x="390" y="${titleY + 280}" width="300" height="52" rx="8" fill="#8B6914"/>
  <text x="540" y="${titleY + 314}" font-family="Georgia,serif" font-size="22" fill="#1a1208" text-anchor="middle">${escapeXml(r.mood ?? r.cuisineInspiration)}</text>
  <!-- Savora wordmark -->
  <text x="${svgWidth - 48}" y="${svgHeight - 40}" font-family="Georgia,serif" font-size="28" fill="#f5f0e8" text-anchor="end" font-variant="small-caps">savora</text>
  <!-- Generated by -->
  <text x="48" y="${svgHeight - 40}" font-family="Georgia,serif" font-size="20" fill="#6b6055" text-anchor="start">Generated by Savora</text>
</svg>`;

    res.setHeader('Content-Type', 'image/svg+xml');
    res.setHeader('Content-Disposition', `attachment; filename="${r.title.replace(/[^a-z0-9]/gi, '_')}_card.svg"`);
    res.send(svg);
  } catch (err) {
    console.error('Share card error:', err);
    res.status(500).json({ error: 'Failed to generate share card' });
  }
});

function wrapText(text: string, maxChars: number): string[] {
  const words = text.split(' ');
  const lines: string[] = [];
  let current = '';
  for (const word of words) {
    if ((current + ' ' + word).trim().length > maxChars) {
      if (current) lines.push(current);
      current = word;
    } else {
      current = (current + ' ' + word).trim();
    }
  }
  if (current) lines.push(current);
  return lines;
}

function escapeXml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

export default router;
